# This is a basic workflow to help you get started with Actions
# This scans the Riches Application Release on FOD known as https://ams.fortify.com/Applications/118594

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" where it both builds the code and then delivers the packaged code to FOD for a security scan.
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Java 8 required by ScanCentral Client and FoD Uploader (Univeral CI Tool)
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs a single command using the runners shell
      #- name: Run a one-line script
        #run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
        #run: |
          #echo Add other actions to build,
          #echo test, and deploy your project.
      
      # Prepare source+dependencies for upload. 
      # Update PACKAGE_OPTS based on the ScanCentral Client documentation and your project's included tech stack(s).
      #   ScanCentral Client will download dependencies for maven, gradle and msbuild projects.
      #   For other build tools, add your build commands to the workflow to download necessary dependencies and prepare according to Fortify on Demand Packaging documentation.
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1
      - name: Package Code + Dependencies
        run: scancentral package $PACKAGE_OPTS -o codepackage.zip
        env:
          PACKAGE_OPTS: "-bt none"
      
      # Package code for FOD delivery
      #- uses: montudor/action-zip@v1
        #with:
          #args: zip -qq -r codepackage.zip . -i dir
      
      # Start Fortify on Demand SAST scan and wait until results complete. Be sure to set secrets/variables for your FoD tenant.
        # Following code copied 2021-05-13 from https://github.com/fortify/gha-sample-workflows-ssc-js-sandbox/actions/runs/635878295/workflow
      - name: Download Fortify on Demand Universal CI Tool
        uses: fortify/gha-setup-fod-uploader@v1
      - name: Perform SAST Scan
        run: java -jar $FOD_UPLOAD_JAR -z codepackage.zip -aurl $FOD_API_URL -purl $FOD_BASE_URL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -ac "$FOD_API_KEY" "$FOD_API_SECRET" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
        #run: java -jar $FOD_UPLOAD_JAR -z codepackage.zip -aurl https://api.ams.fortify.com -purl https://ams.fortify.com -rid "219788" -tc "franklinbank" -ac "606f6480-f65f-4bbb-87f7-9e0517abc94e" "ejBnSFJAMEJZLWJ3T0V1ZmQqTTNEM0hUaVk1Qm1y0" -ep 2 -pp 0 -I 1 -apf -n "$FOD_UPLOADER_NOTES"
        env: 
          FOD_TENANT: ${{ secrets.FOD_TENANT }}  
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_API_KEY: ${{ secrets.FOD_API_KEY }}
            #FOD_API_KEY - using an API Key with StartScan permissions only
          FOD_API_SECRET: ${{ secrets.FOD_API_SECRET }}
          FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}
            #e.g. 219788 for Riches.JAVA on franklinbank tenant
          FOD_BASE_URL: ${{ secrets.FOD_BASE_URL }}
            #e.g. https://ams.fortify.com/
          FOD_API_URL: ${{ secrets.FOD_API_URL }}
            #e.g. https://api.ams.fortify.com/
          FOD_UPLOADER_OPTS: "-ep 2 -pp 0 -I 1 -apf"
          FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
      
      # Once FOD scan completes, pull SAST issues from Fortify On Demand and generate SARIF output.
      - name: Download Results
        uses: fortify/gha-export-vulnerabilities@v1
        with:
          FOD_BASE_URL: ${{ secrets.FOD_BASE_URL }}
            #e.g. https://ams.fortify.com/
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}
          FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}
            #e.g. 219788 for Riches.JAVA on franklinbank tenant
      
      # Import Fortify On Demand results to GitHub Security Code Scanning - in SARIF format
      - name: Import Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./gh-fortify-sast.sarif
